/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatLightLaf;
import dao.AccountDAO;
import dao.CourseService;
import dao.LessonService;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.Lesson;
import model.Course;

/**
 *
 * @author Hoan
 */
public class AddLesson extends javax.swing.JDialog {

    /**
     * Creates new form AddAccount
     */
    private LessonForm parent;
    LessonService daoLesson = null;
    CourseService daoCourse = null;
    AccountDAO daoUser = null;
    public AddLesson(javax.swing.JInternalFrame parent, javax.swing.JFrame owner, boolean modal) throws SQLException {
        super(owner, modal);
        this.parent = (LessonForm) parent;
        initComponents();
        daoUser = new AccountDAO();
        daoCourse = new CourseService(daoUser);
        daoLesson = new LessonService(daoCourse);
        ArrayList<Course> courses = daoCourse.selectAll();
        setComboboxCourse(courses); 
        setLocationRelativeTo(null);
        txtIdLesson.setText(createIdLT());
        txtIdLesson.setEditable(false);
    }


    
    public void setComboboxCourse(ArrayList<Course> arr) {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Course course : arr) {
            model.addElement(course.getName());
        }
        cbxKhoaHoc.setModel(model); 
    }
    
    
    public String createIdLT() {
        ArrayList<Lesson> lessons = daoLesson.selectAll();
        int maxId = 0;
        for (Lesson lesson : lessons) {
            int currentId = (lesson.getId());
            if (currentId > maxId) {
                maxId = currentId;
            }
        }
        return "" + (maxId + 1);
    }


    public String setOrderLesson(ArrayList<Lesson> arr) {
        int maxOrder = 0;
        for (Lesson lesson : arr) {
            int currentOrder = (lesson.getOrder());
            if (currentOrder > maxOrder) {
                maxOrder = currentOrder;
            }
        }
        return "" + (maxOrder + 1);
    }
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdLesson = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtmota = new javax.swing.JTextField();
        cbxKhoaHoc = new javax.swing.JComboBox<>();
        cbxVideo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm tài khoản mới");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jLabel2.setText("Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, -1));

        txtIdLesson.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jPanel1.add(txtIdLesson, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 298, 38));

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jLabel3.setText("Tiêu Đề");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 24));

        txtTitle.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jPanel1.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 298, 38));

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jLabel4.setText("Mô Tả");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 100, -1));

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jLabel5.setText("Khóa Học");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 80, -1));

        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jButton1.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 140, 38));

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Huỷ");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 140, 38));

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THÊM BÀI HỌC MỚI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 70));

        txtmota.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jPanel1.add(txtmota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 298, 38));

        cbxKhoaHoc.setFont(new java.awt.Font("SF Pro Display", 0, 15)); // NOI18N
        cbxKhoaHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Tiêu Đề", "Mô Tả", "Khóa Học", " " }));
        cbxKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxKhoaHocActionPerformed(evt);
            }
        });
        jPanel1.add(cbxKhoaHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 300, 40));

        cbxVideo.setFont(new java.awt.Font("SF Pro Display", 0, 15)); // NOI18N
        cbxVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVideoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 300, 40));

        jLabel6.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jLabel6.setText("Video");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtIdLesson.getText().trim());
            String title = txtTitle.getText().trim();
            String mota = txtmota.getText().trim();
            String khoahoc = cbxKhoaHoc.getSelectedItem().toString();
            if (title.equals("") || mota.equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            } else {
                
                Lesson lesson = new Lesson();
                lesson.setId(id);
                lesson.setTitle(title);
                lesson.setDescription(mota);
                Course course = daoCourse.find(khoahoc);
                String order = setOrderLesson(daoLesson.selectByIdCourse(course.getId()));
                lesson.setOrder(Integer.parseInt(order));
                lesson.setCourse(course);
                daoLesson.insert(lesson);
                parent.loadDataToTable(daoLesson.selectAll());
                this.dispose();
            }
        } catch (Exception ex) {
             ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbxKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxKhoaHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxKhoaHocActionPerformed

    private void cbxVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVideoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxVideoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxKhoaHoc;
    private javax.swing.JComboBox<String> cbxVideo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtIdLesson;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtmota;
    // End of variables declaration//GEN-END:variables
}
