/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatLightLaf;
import com.mysql.cj.protocol.Resultset;
import com.sun.jdi.connect.spi.Connection;
import controller.Hash;
import dao.AccountDAO;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

import model.Account;

/**
 *
 * @author Hoan
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    Connection con = null;
    Resultset rs = null;
    Color panDefualt, panEnter, panClick;

    public Register() {
        initComponents();
        setLocationRelativeTo(null);
        UIManager.put("Button.focus", Color.white);
        panDefualt = new Color(89, 168, 105);
        panClick = new Color(89, 168, 120);
        panEnter = new Color(89, 168, 120);
       
        ImageIcon logo = new ImageIcon(getClass().getResource("/icon/logo.png"));
        setIconImage(logo.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        passwordUser1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        loginUser1 = new javax.swing.JTextField();
        JPaneRegister1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập vào phần mềm");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(13, 39, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Đăng ký");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 270, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 580));

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 110, 40));

        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 260, 0));

        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 194, 260, -1));

        txtemail.setBackground(new java.awt.Color(13, 39, 51));
        txtemail.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        txtemail.setForeground(new java.awt.Color(255, 255, 255));
        txtemail.setBorder(null);
        txtemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtemailMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtemailMousePressed(evt);
            }
        });
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemailKeyPressed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 260, 30));

        jLabel8.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 130, 40));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "teacher", "student" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 270, 40));

        passwordUser1.setBackground(new java.awt.Color(13, 39, 51));
        passwordUser1.setForeground(new java.awt.Color(255, 255, 255));
        passwordUser1.setBorder(null);
        passwordUser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordUser1KeyPressed(evt);
            }
        });
        jPanel1.add(passwordUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 260, 30));

        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 260, -1));

        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 260, 0));

        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 312, 260, -1));

        jLabel11.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 130, 40));

        loginUser1.setBackground(new java.awt.Color(13, 39, 51));
        loginUser1.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        loginUser1.setForeground(new java.awt.Color(255, 255, 255));
        loginUser1.setBorder(null);
        loginUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginUser1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginUser1MousePressed(evt);
            }
        });
        loginUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUser1ActionPerformed(evt);
            }
        });
        loginUser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginUser1KeyPressed(evt);
            }
        });
        jPanel1.add(loginUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 260, 30));

        JPaneRegister1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        JPaneRegister1.setToolTipText("");
        JPaneRegister1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPaneRegister1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPaneRegister1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPaneRegister1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPaneRegister1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPaneRegister1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JPaneRegister1MouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Đăng ký");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JPaneRegister1Layout = new javax.swing.GroupLayout(JPaneRegister1);
        JPaneRegister1.setLayout(JPaneRegister1Layout);
        JPaneRegister1Layout.setHorizontalGroup(
            JPaneRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPaneRegister1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        JPaneRegister1Layout.setVerticalGroup(
            JPaneRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPaneRegister1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(JPaneRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 270, 40));

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thoát");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 105, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtemailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemailMouseEntered
        // TODO add your handling code here:    
    }//GEN-LAST:event_txtemailMouseEntered

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        System.out.println(evt.getKeyCode());

    }//GEN-LAST:event_formKeyPressed

    private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Enter was pressed. Your code goes here.
            checkRegister();
        }
    }//GEN-LAST:event_txtemailKeyPressed

    private void txtemailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemailMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtemailMousePressed

    private void passwordUser1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordUser1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordUser1KeyPressed

    private void loginUser1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginUser1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUser1MouseEntered

    private void loginUser1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginUser1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUser1MousePressed

    private void loginUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUser1ActionPerformed

    private void loginUser1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginUser1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUser1KeyPressed

    private void JPaneRegister1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPaneRegister1MouseClicked
        // TODO add your handling code here:
        checkRegister();
    }//GEN-LAST:event_JPaneRegister1MouseClicked

    private void JPaneRegister1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPaneRegister1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPaneRegister1MouseEntered

    private void JPaneRegister1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPaneRegister1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPaneRegister1MouseExited

    private void JPaneRegister1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPaneRegister1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPaneRegister1MousePressed

    private void JPaneRegister1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPaneRegister1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JPaneRegister1MouseReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
      
        checkRegister();
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(new FlatLightLaf());

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    public void checkRegister() {
    String usercheck = loginUser1.getText();
    String passwordcheck = passwordUser1.getText();
    String role = jComboBox1.getSelectedItem().toString();
    String email = txtemail.getText();
//    System.out.println("Attempting login with username: " + usercheck);
    if (usercheck.equals("") || passwordcheck.equals("") || txtemail.equals("")) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ !", "Cảnh báo !", JOptionPane.WARNING_MESSAGE);
    } else {
        
        try {
            AccountDAO dao = new AccountDAO();
            Account acc = dao.find(usercheck);
            System.out.println("User found: " + (acc != null));
            if (acc != null) {
                JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại trên hệ thống !", "Cảnh báo !", JOptionPane.WARNING_MESSAGE);
            } else {
                if(!isValid(email)){
                    JOptionPane.showMessageDialog(this, "email không đúng định dạng !", "Cảnh báo !", JOptionPane.WARNING_MESSAGE);
                }else{
                    Account account = new Account();
                    account.setUserName(usercheck);
                    account.setPassword(passwordcheck);
                    account.setEmail(email);
                    account.setRole(role);
                    account.setStatus(1);
                    dao.insert(account);
                    JOptionPane.showMessageDialog(this, "Tạo tài khoản thành công !", "Thành công !", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
    
    static boolean isValid(String email) {
        String regex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        return email.matches(regex);
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPaneRegister1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField loginUser1;
    private javax.swing.JPasswordField passwordUser1;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
